name: diabetes-sklearn-mlp
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install packages and run scripts
          sudo -H pip install -r requirements.txt
          python 02_sklearn_MLP.py
          
          # Publich metrics
          echo "## Model Metrics" > report.md
          cat sklearn_metrics.txt >> report.md

          # Add charts
          cml-publish sklearn_mlp_loss_curve.png --md >> report.md

          # Generate report
          cml-send-comment report.md
