name: dvc-pipeline
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro

          git fetch --prune

          # Add chart
          echo "## Neural Network Loss Overtime" >> report.md
          cml-publish ./images/sklearn_mlp_loss_curve.png --md >> report.md
          
          # Show metrics
          echo "## Accuracy Metrics" >> report.md
          cat ./metrics/train_metrics.json >> report.md
          
          cml-send-comment report.md